language: ruby

arch: arm64

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GLOBAL_METHOD_CACHE_SIZE=131072
  matrix:
    - "RAILS_MASTER=0 QUNIT_RUN=0 RUN_LINT=0"
    
addons:
  chrome: stable
  postgresql: 9.6
  apt:
    update: true
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

matrix:
  fast_finish: true

rvm:
  - 2.5.1

services:
  - redis-server

sudo: required
dist: trusty

cache:
  apt: true
  yarn: true
  directories:
    - vendor/bundle

before_install:
  - gem install bundler
  - git clone --depth=1 https://github.com/discourse/discourse-backup-uploads-to-s3.git plugins/discourse-backup-uploads-to-s3
  - git clone --depth=1 https://github.com/discourse/discourse-spoiler-alert.git plugins/discourse-spoiler-alert
  - git clone --depth=1 https://github.com/discourse/discourse-cakeday.git plugins/discourse-cakeday
  - git clone --depth=1 https://github.com/discourse/discourse-canned-replies.git plugins/discourse-canned-replies
  - git clone --depth=1 https://github.com/discourse/discourse-chat-integration.git plugins/discourse-chat-integration
  - git clone --depth=1 https://github.com/discourse/discourse-assign.git plugins/discourse-assign
  - git clone --depth=1 https://github.com/discourse/discourse-patreon.git plugins/discourse-patreon
  - git clone --depth=1 https://github.com/discourse/discourse-staff-notes.git plugins/discourse-staff-notes
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - bash -c "if [ '$RAILS_MASTER' == '1' ]; then bundle update --retry=3 --jobs=3 arel rails seed-fu > /dev/null; fi"
  - bash -c "if [ '$RAILS_MASTER' == '0' ]; then bundle install --without development --deployment --retry=3 --jobs=3 > /dev/null; fi"
  - bash -c "if [ '$RUN_LINT' == '1' ]; then yarn global add eslint babel-eslint > /dev/null; fi"
  - bash -c "if [ '$QUNIT_RUN' == '1' ]; then yarn install --dev > /dev/null; fi"
  - cd vendor/bundle/ruby/2.5.0/gems/mini_suffix-0.3.0/vendor/
  - wget http://mirror.archlinuxarm.org/aarch64/core/libpsl-0.21.1-1-aarch64.pkg.tar.xz
  - tar -xvf libpsl-0.21.1-1-aarch64.pkg.tar.xz
  - cp -rf usr/lib/libpsl.so.5.3.3 .
  - rm -rf libpsl.so 
  - mv libpsl.so.5.3.3 libpsl.so
  #- rails --version
  #- rake --tasks
  - gem install rspec
  - bash -c "if [ '$RUN_LINT' != '1' ]; then bundle exec rake db:create db:migrate > /dev/null; fi"

script:
  - |
    bash -c "
      if [ '$RUN_LINT' == '1' ]; then
        bundle exec rubocop --parallel && \
        eslint --ext .es6 app/assets/javascripts && \
        eslint --ext .es6 test/javascripts && \
        eslint --ext .es6 plugins/**/assets/javascripts && \
        eslint --ext .es6 plugins/**/test/javascripts && \
        eslint app/assets/javascripts test/javascripts
      else
        if [ '$QUNIT_RUN' == '1' ]; then
          bundle exec rake qunit:test['500000'] && \
          bundle exec rake plugin:qunit
        else
          bundle exec rspec && bundle exec rake plugin:spec
        fi
      fi
    "
